UnboundLocalError: local variable 'DownloadFromWeb' referenced before assignment
Gathering details needed for 'dist-upgrade' operation

Fetching APT Data

Traceback (most recent call last):
  File "/home/rrs/rrs-home/devel/apt-offline/apt-offline/apt-offline", line 28, in <module>
    main()
  File "/home/rrs/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 2484, in main
    args.func(args)
  File "/home/rrs/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1083, in fetcher
    DownloadFromWeb = DownloadFromWeb
UnboundLocalError: local variable 'DownloadFromWeb' referenced before assignment

A price to pay when not good with names. Otherwise too, a good practice
should be to NOT use clashing names in variables/classes.