Handle exception particular to some files only
It throws this exception only for one package, in this case
transmission-common. So it may be related to damaged payload.

For now, handle it this way until cause it known.

We can't abort the entire operation, as usual, because this failure is
not fatal to the entire workflow

rrs@learner:~/.rrs-home/devel/apt-offline/apt-offline (refactor)$ ./apt-offline get /var/tmp/changelog.uris  --download-dir /var/tmp/changelog/ --threads 5 --cache-dir /var/cache/apt/archives/

Fetching APT Data

WARNING: If you are on a slow connection, it is good to
WARNING: limit the number of threads to a low number like 2.
WARNING: Else higher number of threads executed could cause
WARNING: network congestion and timeouts.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 669, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1153, in DataFetcher
    FetcherInstance.buildChangelog(full_file_path, PackageInstalledVersion[PackageName])
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1033, in buildChangelog
    chlogFile.writelines(pkgHandle.data_content(pkgFile))
TypeError: writelines() argument must be a sequence of strings

  5 /   6 items: [##############################] 100.0% of 1 MiBiB
Downloaded data to /var/tmp/changelog/
2016-06-06 / 19:59:10 ♒♒♒  ☺