Set encoding for files when opening
There are some more instances where we open file without specifying an
econding. Should we specify there too ?

The reason why this showed up here is because this part of the code
deals with the changelog, which can have special characters in its
content.

I'm inclined to use the same rationale for other parts of the code too,
namely bug report handling etc, but my understanding of character
encodings is very limited.

Thus, lets wait for some time and see if this issue shows up elsewhere
too.

Closes: https://github.com/rickysarraf/apt-offline/issues/126

This issue this commit fixes is:

root@debhurd:~# apt-offline  get /tmp/set.uris --bundle /tmp/set.zip --threads 5 --proxy-host aptproxy --proxy-port 3142

Fetching APT Data

WARNING: If you are on a slow connection, it is good to
WARNING: limit the number of threads to a low number like 2.
WARNING: Else higher number of threads executed could cause
WARNING: network congestion and timeouts.

Downloading initscripts - 56 KiB
Downloading sysv-rc - 32 KiB
Downloading xxd - 152 KiB
Downloading netdde - 847 KiB
Downloading sysvinit-utils - 24 KiB
sysvinit-utils done
sysv-rc done
initscripts done
xxd done
Downloading libboost-regex1.71.0 - 501 KiB
Downloading gdb - 2 MiB
Exception in thread Thread-1:#####              ]  55.0% of 1 MiB
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 696, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1298, in DataFetcher
    FetcherInstance.buildChangelog(pkgFile, PackageInstalledVersion[PackageName])
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1131, in buildChangelog
    chlogFile.writelines(pkgHandle.data_content(pkgFile))
  File "/usr/lib/python3.6/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character '\xb3' in position 0: ordinal not in range(128)

Exception ignored in: <_io.FileIO name='/tmp/xxd.changelog' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/xxd.changelog' mode='w' encoding='ANSI_X3.4-1968'>
Downloading sysvinit-core - 148 KiB
netdde done
sysvinit-core done
libboost-regex1.71.0 done
Downloading debianutils - 97 KiB
Downloading bash - 1 MiB
Exception in thread Thread-5:################## ]  96.3% of 4 MiB
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 696, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1298, in DataFetcher
    FetcherInstance.buildChangelog(pkgFile, PackageInstalledVersion[PackageName])
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1131, in buildChangelog
    chlogFile.writelines(pkgHandle.data_content(pkgFile))
  File "/usr/lib/python3.6/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0410' in position 0: ordinal not in range(128)

Exception ignored in: <_io.FileIO name='/tmp/sysvinit-core.changelog' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/sysvinit-core.changelog' mode='w' encoding='ANSI_X3.4-1968'>
gdb done
debianutils done