Better error logging when apt fails
Closes: https://github.com/rickysarraf/apt-offline/issues/83

So apt already does report an error which apt-offline displays well.

rrs@priyasi:~/.../open-iscsi (master)$ sudo apt-offline set /tmp/foo.sig --install-packages wrong-package-name
[sudo] password for rrs:
Gathering installation details for package ['wrong-package-name']
E: Unable to locate package wrong-package-name
ERROR: FATAL: Something is wrong with the apt system.
22:01 ♒ ॐ ♅ ⛢  ☺ 😄

There are 2 issues above.

1. We print a useless message about something being wrong with the apt
system. This is now fixed by demoting the message to verbose. We are
not knocking it off completely because incase apt changes its behavior
and not display anything, we'll still know in verbose that apt was
failing.

2. Even though the above operation is a failure, apt-offline's exit
status is success. This too is now fixed in this change. We carry the
error from the invoked command (we don't carry the invoked command's
status because its error code in most common failures is always 100) and
flash it accordingly.

Final result now is:

Before

rrs@priyasi:~/.../open-iscsi (master)$ sudo apt-offline set /tmp/foo.sig --install-packages wrong-package-name
[sudo] password for rrs:
Gathering installation details for package ['wrong-package-name']
E: Unable to locate package wrong-package-name
ERROR: FATAL: Something is wrong with the apt system.
22:01 ♒ ॐ ♅ ⛢  ☺ 😄

Now, with this change:

rrs@priyasi:~/.../apt-offline (master)$ sudo ./apt-offline set /tmp/foo.sig --install-packages wrong-package-name
Gathering installation details for package ['wrong-package-name']
E: Unable to locate package wrong-package-name
22:15 ♒ ॐ ♅ ⛢   ☹ 😟=> 1