Add SSLError to namespace
Because this exception is originated from debianbts; and someone has to
handle it.

libapt-inst2.0 copied from local cache directory /var/cache/apt/archives/                               No handlers could be found for logger "pysimplesoap.simplexml"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 642, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1079, in DataFetcher
    if FetchBugReportsDebian.FetchBugsDebian(PackageName) in [1,2]:
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 174, in FetchBugsDebian
    except SSLError:
NameError: global name 'SSLError' is not defined

 38 / 114 items: [##########################    ]  87.4% of 14 MiB
Downloaded data to /var/tmp/upgrade.zip
2016-05-12 / 15:33:59 ♒♒♒  ☺