Fix exception in Bug List GUI
The format of the bugreport file is common. So this code was wrong day
one.

Traceback (most recent call last):
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_gui/AptOfflineQtInstall.py", line 124, in showBugReports
    self.bugReportsDialog = AptOfflineQtInstallBugList(self.filepath)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_gui/AptOfflineQtInstallBugList.py", line 19, in __init__
    self.populateBugList(self.filepath)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_gui/AptOfflineQtInstallBugList.py", line 68, in populateBugList
    bugNumber = filename.split(".")[1]
IndexError: list index out of range
2016-11-03 / 22:54:07 ♒♒♒  ☺