Handle Checksum for IndexError
The 4th item, i.e. Checksum is not applicable for Release and
Release.gpg uris. For these items, there is an IndexError raised for
some reason on some user reports. Don't know why.
But anyway, we can handle this when getting IndexErrr by checking if the
item uri is Release and if so we set checksum to None

19:50:55 rrs@champaran:~/devel/apt-offline/apt-offline  (george-bug)$
./apt-offline get /tmp/george.list  --verbose
VERBOSE: Namespace(bundle_file=None, cache_dir=None, deb_bugs=False,
disable_md5check=False, download_dir=None, func=<function fetcher at
0x7fbe51afa230>, get='/tmp/george.list', num_of_threads=1,
simulate=False, socket_timeout=30, verbose=True)
VERBOSE: Default timeout now is: 30.

Fetching APT Data

VERBOSE: Item is
["'http://ftp.tw.debian.org/debian/dists/testing/Release'",
'ftp.tw.debian.org_debian_dists_testing_Release', '0\n']
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.5/threading.py", line 486, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.5/threading.py", line 446, in run
    self.__target(*self.__args, **self.__kwargs)
  File
"/home/rrs/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py",
line 578, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File
"/home/rrs/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py",
line 548, in DataFetcher
    (url, file, download_size, checksum) = stripper(item)
  File
"/home/rrs/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py",
line 308, in stripper
    checksum = string.rstrip(string.lstrip(''.join(item[3]), chars =
"'"), chars = "'")
IndexError: list index out of range