Fix python3 glitch with byte type object
Closes: https://github.com/rickysarraf/apt-offline/issues/74

sid-container:~/apt-offline# ./apt-offline install ../update.zip --verbose
VERBOSE: Namespace(allow_unauthenticated=False, func=<function installer at 0x7f614fee0ea0>, install='../update.zip', install_src_path=None, simulate=False, skip_bug_reports=False, skip_changelog=False, verbose=True)
No changelog available
(Y) Yes. Proceed with installation
(N) No, Abort.
(C) Display changelog
(?) Display this help message.
What would you like to do next:	 (y, N, ?)y
Proceeding with installation
VERBOSE: {}
VERBOSE: Great!!! No bugs found for all the packages that were downloaded.

VERBOSE: File is httpredir.debian.org_debian_dists_sid_Release.gpg, hence 'True'.
VERBOSE: httpredir.debian.org_debian_dists_sid_Release.gpg file synced to APT.
VERBOSE: httpredir.debian.org_debian_dists_sid_InRelease file synced to APT.
VERBOSE: httpredir.debian.org_debian_dists_sid_Release file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_contrib_binary-amd64_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_contrib_binary-all_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_main_binary-all_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_non-free_binary-amd64_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_contrib_i18n_Translation-en file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_non-free_binary-all_Packages file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_non-free_i18n_Translation-en file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_main_i18n_Translation-en file synced to APT.
VERBOSE: /var/lib/apt/lists/partial/httpredir.debian.org_debian_dists_sid_main_binary-amd64_Packages file synced to APT.
Hello

Traceback (most recent call last):
  File "./apt-offline", line 28, in <module>
    main()
  File "/root/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 2212, in main
    args.func(args)
  File "/root/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1918, in installer
    AptSecure = APTVerifySigs(Simulate=InstallerInstance.Bool_TestWindows)
  File "/root/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 594, in __init__
    output = process.communicate(input=command)[0]
  File "/usr/lib/python3.5/subprocess.py", line 803, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1441, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'str'
sid-container:~/apt-offline