Try harder to create a clean signature
This happens with build-dep and src-build-dep when certain dependencies
are not satisfied in the archive

Up till now, DownloadFromWeb will throw this exception because,
obviously, splitter() failed to understand that line

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 636, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 846, in DataFetcher
    if DownloadPackages(url) is False and guiTerminateSignal is False:
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 820, in DownloadPackages
    if FetcherInstance.download_from_web(url, pkgFile, Str_DownloadDir) == True:
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 259, in download_from_web
    temp = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 423, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 285, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type:

Culprit is this signature. An example of a corrupt signature

rrs@learner:/media/SSHD/rrs-home/devel/apt-offline/apt-offline (master)$ cat /tmp/set-31788.uris
'http://ftp.debian.org/debian/pool/main/l/lxde-metapackages/lxde-metapackages_6.dsc' lxde-metapackages_6.dsc 1727 SHA256:e78f577bf6ee8c86590b5d53deda503e9778e5d2aeb11ed2404cfa2ccbfe62e8
'http://ftp.debian.org/debian/pool/main/l/lxde-metapackages/lxde-metapackages_6.tar.xz' lxde-metapackages_6.tar.xz 3260 SHA256:d64464520c0629d2db8420559dd31e16d7a126222656c8337d98f9019c631339
'http://ftp.debian.org/debian/pool/main/i/icewm/icewm_1.3.8+githubmod+20150914+fa3fdef-2.dsc' icewm_1.3.8+githubmod+20150914+fa3fdef-2.dsc 2315 SHA256:e0b581a34de44a9d8a2f529c72ab5c8f1fcad084077e89a939b93b9f18b2b9ee
'http://ftp.debian.org/debian/pool/main/i/icewm/icewm_1.3.8+githubmod+20150914+fa3fdef.orig.tar.xz' icewm_1.3.8+githubmod+20150914+fa3fdef.orig.tar.xz 560644 SHA256:72a044020f61b31a02b372db09e3da455f7e425f9e688c5c58fbbff68d3e2ab2
'http://ftp.debian.org/debian/pool/main/i/icewm/icewm_1.3.8+githubmod+20150914+fa3fdef-2.debian.tar.xz' icewm_1.3.8+githubmod+20150914+fa3fdef-2.debian.tar.xz 81756 SHA256:564a6baf697a728325b126476a206c3cdaaf3259d447a5fad47d5c7f522b1c5e
'http://ftp.debian.org/debian/pool/main/e/eclipse/eclipse_3.8.1-8.dsc' eclipse_3.8.1-8.dsc 3091 SHA256:a4274d909686f2e724d9d5b7b139b35daec45fa31e704bc71191d97b2be1e8e3
'http://ftp.debian.org/debian/pool/main/e/eclipse/eclipse_3.8.1.orig.tar.xz' eclipse_3.8.1.orig.tar.xz 47855736 SHA256:7ceb45ced36f870163b5e64c950f2fcf2a9ebdb85edf5953677c883c32a09b62
'http://ftp.debian.org/debian/pool/main/e/eclipse/eclipse_3.8.1-8.debian.tar.xz' eclipse_3.8.1-8.debian.tar.xz 101388 SHA256:d1c4a395a964687bd8648f576bd01e328273d7ad71b46322b711709a46076d05
The following packages have unmet dependencies:
 libgdk-pixbuf2.0-dev : Depends: libpng12-dev but it is not going to be installed
 libxft-dev : Depends: libfontconfig1-dev but it is not going to be installed
              Depends: libfreetype6-dev but it is not going to be installed
2015-10-31 / 19:34:27 ♒♒♒  ☺

And now, with this fix. We truncate, when we sense there was an error

rrs@learner:/media/SSHD/rrs-home/devel/apt-offline/apt-offline (master)$ cat /tmp/set-32168.uris
'http://ftp.debian.org/debian/pool/main/l/lxde-metapackages/lxde-metapackages_6.dsc' lxde-metapackages_6.dsc 1727 SHA256:e78f577bf6ee8c86590b5d53deda503e9778e5d2aeb11ed2404cfa2ccbfe62e8
'http://ftp.debian.org/debian/pool/main/l/lxde-metapackages/lxde-metapackages_6.tar.xz' lxde-metapackages_6.tar.xz 3260 SHA256:d64464520c0629d2db8420559dd31e16d7a126222656c8337d98f9019c631339
'http://ftp.debian.org/debian/pool/main/i/icewm/icewm_1.3.8+githubmod+20150914+fa3fdef-2.dsc' icewm_1.3.8+githubmod+20150914+fa3fdef-2.dsc 2315 SHA256:e0b581a34de44a9d8a2f529c72ab5c8f1fcad084077e89a939b93b9f18b2b9ee
'http://ftp.debian.org/debian/pool/main/i/icewm/icewm_1.3.8+githubmod+20150914+fa3fdef.orig.tar.xz' icewm_1.3.8+githubmod+20150914+fa3fdef.orig.tar.xz 560644 SHA256:72a044020f61b31a02b372db09e3da455f7e425f9e688c5c58fbbff68d3e2ab2
'http://ftp.debian.org/debian/pool/main/i/icewm/icewm_1.3.8+githubmod+20150914+fa3fdef-2.debian.tar.xz' icewm_1.3.8+githubmod+20150914+fa3fdef-2.debian.tar.xz 81756 SHA256:564a6baf697a728325b126476a206c3cdaaf3259d447a5fad47d5c7f522b1c5e
'http://ftp.debian.org/debian/pool/main/e/eclipse/eclipse_3.8.1-8.dsc' eclipse_3.8.1-8.dsc 3091 SHA256:a4274d909686f2e724d9d5b7b139b35daec45fa31e704bc71191d97b2be1e8e3
'http://ftp.debian.org/debian/pool/main/e/eclipse/eclipse_3.8.1.orig.tar.xz' eclipse_3.8.1.orig.tar.xz 47855736 SHA256:7ceb45ced36f870163b5e64c950f2fcf2a9ebdb85edf5953677c883c32a09b62
'http://ftp.debian.org/debian/pool/main/e/eclipse/eclipse_3.8.1-8.debian.tar.xz' eclipse_3.8.1-8.debian.tar.xz 101388 SHA256:d1c4a395a964687bd8648f576bd01e328273d7ad71b46322b711709a46076d05
2015-10-31 / 19:38:07 ♒♒♒  ☺