Only evaluate name of the file
Calling os.path.samefile was a bad idea. Resulted in following exception
because we are checking for the name, to avoid collisions.

Hence, revert back to simple string comparison

Closes: https://github.com/rickysarraf/apt-offline/issues/55

gcc-6-base done
gcc-6-base_6.1.1-9_amd64.deb /var/cache/apt/archives/gcc-6-base_6.1.1-9_amd64.deb
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 678, in run
    self.responseQueue.put( self.WorkerFunction( item, thread_name ) )
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1198, in DataFetcher
    FetcherInstance.writeToCache(pkgFile)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineCoreLib.py", line 1017, in writeToCache
    self.copy_file(data, self.CacheDir)
  File "/media/SSHD/rrs-home/devel/apt-offline/apt-offline/apt_offline_core/AptOfflineLib.py", line 556, in copy_file
    if os.path.samefile(src, destFile):
  File "/usr/lib/python2.7/posixpath.py", line 156, in samefile
    s2 = os.stat(f2)
OSError: [Errno 2] No such file or directory: '/var/cache/apt/archives/gcc-6-base_6.1.1-9_amd64.deb'